### ISSUE TITLE
Replace `moxios` with an alternative

### ISSUE THREAD

**Issue by nelsonleite** [Farfetch/blackout#18]
## Is your proposal related to a problem?

`moxios` seems to be incompatible with `axios` after version 0.19.1, as reported [here](https://github.com/axios/axios/issues/2650). Besides, `moxios` latest release is 4+ years old.

The seems to be not in `moxios` actually but rather in `axios` itself and the problem was that after `axios` version 0.18, the code that was concatenating the `baseURL` with the URL of the request was done before much earlier and now it is done on each `axios` adapter class (There is an adapter for XHR requests and HTTP requests). Now, `moxios` replaces these adapters with its own `mockAdapter`, so the code that built the full URL was now not being executed.

## Describe the solution you'd like

**Possible options**

- [nock](https://github.com/nock/nock)
- [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter)
- [msw](https://github.com/mswjs/msw)

Here is a [comparative](https://www.npmtrends.com/fetch-mock-vs-moxios-vs-nock) between them.

The team chooses MSW.

- [x] addresses
- [ ] ~~analyticsService~~
- [x] authentication
- [x] bags
- [x] brands
- [x] categories
- [x] checkout
- [x] contents
- [x] designers
- [x] forms
- [x] language
- [x] locale
- [x] loyalty
- [x] merchantsLocations
- [ ] ~~oAuth~~
- [x] omnitracking
- [x] orders
- [x] payments
- [x] products
- [x] promotionEvaluations
- [x] recentlyViewed
- [x] recommendations
- [x] returns
- [x] search
- [x] settings
- [x] siteFeatures
- [x] sizeGuides
- [x] sizeScales
- [x] staffMembers
- [x] subscriptions
- [x] users
- [x] wishlists

**Comment by jhairabreu** [comment]
closed by https://github.com/Farfetch/blackout/pull/347
