### ISSUE TITLE
Head component throws error

### ISSUE THREAD

**Issue by franciscomacedobrito** [Farfetch/blackout#194]
## Expected behavior

When running unit tests along with a client-side application the described error  should not be thrown

## Actual behavior

When using this component and running unity tests with Jest the following error is thrown:
![image-20220214-094146](https://user-images.githubusercontent.com/21694245/154250568-db078aee-0abf-41fd-881e-3f021f76ba12.png)
The component to be inspected is:
https://github.com/Farfetch/blackout/blob/main/packages/react/src/content/components/Head.js

## Steps to reproduce

1. Setup the component along with a client-side application
2. Run unit tests using Jest

**Comment by jtcode12** [comment]
Hey can I try this?

**Comment by franciscomacedobrito** [comment]
After doing a deeper analysis it was found that the issue was on an internal client-side application when mocking the Head component. For that reason, the issue will be closed and addressed internally.
