### ISSUE TITLE
sortOptionSchema doesn't exist

### ISSUE THREAD

**Issue by AceBunny** [Farfetch/blackout#283]
## Expected behavior

`sortOptionSchema` should exist or the import should be removed

## Actual behavior

`sortOptionSchema` is imported in `packages/react/src/analytics/integrations/GA4/validation/eventSchemas.js` from `packages/react/src/analytics/integrations/shared/validation/eventSchemas.js` but it doesn't exist anywhere in the codebase

## Steps to reproduce

1. HMR bundler shows warning:  ```
./node_modules/@farfetch/blackout-react/src/analytics/integrations/GA4/validation/eventSchemas.js
61:66-82 "export 'sortOptionSchema' was not found in '../../shared/validation/eventSchemas'```

## Possible fix

`sortOptionSchema` should exist or the import should be removed

**Comment by ruifcnunes** [comment]
Hello @AceBunny, this bug was already fixed [here](https://github.com/Farfetch/blackout/pull/281) and will be released next week. 
Thanks for your input anyway 🙂

**Comment by AceBunny** [comment]
Yeah, that seems to fix it, sorry for the inconvenience

**Comment by ruifcnunes** [comment]
No inconvenience at all, feel free to open issues whenever you feel its necessary 🙂  cheers!
