### ISSUE TITLE
Sizes facet naming change doesn't match `filterSegments` in listing results

### ISSUE THREAD

**Issue by desktp** [Farfetch/blackout#296]
## Expected behavior

To get the `sizes` facet on `searchResults` correctly filled.

## Actual behavior

The changes introduced in 1.52.1 related to the naming of the sizes facet, which solved the issue of not discerning from which category that size is, also introduced a problem when getting the search results, because now none of the sizes match, as that info doesn't come correctly filled from the backend either:

![Screenshot_20220509_130318](https://user-images.githubusercontent.com/7454286/167455974-0e24bf18-13f8-4c98-8f3c-55af382fa919.png)

## Steps to reproduce

1. Access https://preview-sacai.blackandwhite-ff.com/en-pt/shopping/women?sizes=20&contextfilters=categories:144307&pageindex=1
2. Open the filters panel through the `Refine` button on the right hand side
3. Check as the pill reads `common.filters.facets.sizes.null`

## Context/environment

* `@farfetch/blackout-core`: `1.55.0`
* `@farfetch/blackout-react`: `0.35.0`

## Additional information

Redux state snapshots:
![Screenshot_20220509_154218](https://user-images.githubusercontent.com/7454286/167456315-7302887c-3229-444e-9cc5-ea9f99e0242c.png)
![Screenshot_20220509_154052](https://user-images.githubusercontent.com/7454286/167456323-3e1539be-6393-4b2a-be11-7bf573252605.png)

## Possible fix

Best case scenario would be actually receiving the proper information from the backend so that the lib can map the facets properly. If that isn't possible, having a fallback when parsing the filter segments so that we don't get `undefined`/`null` values on the description and/or slug.

**Comment by nelsonleite** [comment]
Having the information from the backend it's not possible here; I'll open a PR adding the `facetId` to the `filterSegments` instead 🙂 

With it, you can map directly the filter segment with the respective facet entity.

**Comment by nelsonleite** [comment]
Also added the `description` from the facet, I think this is what you needed for your use case.
