### ISSUE TITLE
Configure lintstaged for projects with multiple packages

### ISSUE THREAD

**Issue by helderburato** [Farfetch/blackout#31]
> In the docs, there is an explanation to configure for projects with multiple packages: [sudo-suhas/lint-staged-multi-pkg](https://github.com/sudo-suhas/lint-staged-multi-pkg)
> 
> What do you think?

I think we can move without this for now, and apply it later, what do you think?

_Originally posted by @joaoprcosta  in https://github.com/Farfetch/blackout/pull/25#issuecomment-977770716_

**Comment by joaoprcosta** [comment]
After checking the proposed solution, we think this improvement is not needed right now as the existing solutions fit our needs.
