### ISSUE TITLE
Missing exports

### ISSUE THREAD

**Issue by desktp** [Farfetch/blackout#323]
## Expected behavior

All exports are correct and defined.

## Actual behavior

In `blackout-react/src/content/helpers/index.js`, missing:
```
export { default as renderContent } from './renderComponent';
```

and in `blackout-react/src/content/utils/sortContentType.js`, missing:
```
export default sortContentType;
```

## Context/environment

Version 0.38.0

**Comment by joaoprcosta** [comment]
Fixed in version 0.39.0
