### ISSUE TITLE
put requests not working correctly

### ISSUE THREAD

**Issue by AceBunny** [Farfetch/blackout#846]
## Expected behavior

`putUserDefaultBillingAddress`, `putUserDefaultContactAddress` and `putUserDefaultShippingAddress` should do their respective requests correctly.

## Actual behavior

Requests from these methods fails because `put` receives `(url: string, data?: Config | undefined, config?: AxiosRequestConfig<Config> | undefined)`.
Currently the methods call `put` like this `client.put(join('/account/v1/users', userId, 'addresses/billing', addressId), config)`, meaning that `config` is being inserted as `data`.
This will make the request 401 because there are no configs added to the request

## Steps to reproduce

1. Call `putUserDefaultBillingAddress(session.userId, addresses[0].id, blackoutConfigs);`
2. This will fail with 401 because of no config being passed

## Context/environment

Reebok

## Possible fix

Add a empty object to fill for `data`

**Comment by boliveira** [comment]
Hi @AceBunny,

I acknowledge this problem. We will work on a fix as soon as possible. Thank you for reporting and sorry for the inconvenience. I will let you know as soon as we have a fix available.

**Comment by boliveira** [comment]
Hi @AceBunny,

Sorry for the delay. Just created a [PR](https://github.com/Farfetch/blackout/pull/856) that fixes this problem and it will be available in next week's release.
